name         'rsyslog'
version 	'RELEASE_1.0.8'
summary      'Install and configure rsyslog.'
description  'Install and configure rsyslog.'
author       'Phil Zimmerman - phil.zimmerman@twcable.com'
project_page 'https://github.webapps.rr.com/fylgia/rsyslog'
