name         'pzimmerman-github-rsyslog'
version 	 'v1.0'
summary      'Install and configure rsyslog.'
description  'Install and configure rsyslog.'
author       'Phil Zimmerman - pzimmerman.home@gmail.com'
project_page 'https://github.com/pzimmerman-github/rsyslog'
